### PR TITLE
Update pip and psutil on travis build.sh

### PR DESCRIPTION
**Pull request by hanslovsky**
This is experimental, might fix travis build issues observed after merging #21
Merge as soon as travis doesn't fail anymore

### CODE REVIEW

**Comment by ctrueden** [comment]
Wouldn't it be better to do:
```diff
diff --git a/setup.py b/setup.py
index 38422ce..e03dfc6 100644
--- a/setup.py
+++ b/setup.py
@@ -24,5 +24,5 @@ setup(
         ]
     },
     python_requires='>=3',
-    tests_require=['nose>=1.0']
+    tests_require=['nose>=1.0', 'psutil']
 )
```
Or would that not work?

**Comment by hanslovsky** [comment]
Will give it a try

**Comment by hanslovsky** [comment]
Will test in this PR, and squash into single commit once it works.

**Comment by hanslovsky** [comment]
Actually, `psutil` should probably go into `install_requires`:
```shell
$ ag --python psutil
jgo/util.py
1:import psutil
23:    total_memory  = psutil.virtual_memory().total
```

**Comment by ctrueden** [comment]
Thanks for testing and pushing the fix, @hanslovsky.

Now that `jgo` requires `psutil`, the conda-forge recipe needs to be updated, right?

**Comment by hanslovsky** [comment]
Yes, that should be reflected in the next (conda) release.

**Pull request merged**
