### PR TITLE
Use sha256 hash of extra coordinates for cache dir name, pepify

### PR DESCRIPTION
**Pull request by kephale**
To address https://github.com/scijava/jgo/issues/31#issuecomment-548056700

### CODE REVIEW

**Comment by hanslovsky** [comment]
Can you push without formatting changes? That will make it easier to review the actual changes.

**Comment by ctrueden** [comment]
I'm a fan of the pepification. I agree with @hanslovsky that doing it as a separate commit would be best.

Here is how I typically tease such things apart using git:

```
git reset HEAD^ # undo the commit
git stash
do-the-pepification # so the unchanged code gets pepified
git commit -a -m 'Pepify!'
git checkout 'stash^{tree}' -- . && git stash drop # force exactly what you stashed back into the working copy
git commit -a -m 'My awesome change, clean this time'
```

**Comment by kephale** [comment]
FWIW, the pepify is with https://github.com/google/yapf which is attached to the python mode in my emacs

**Comment by hanslovsky** [comment]
Thanks @kephale 
I have a pretty busy schedule right now but will try to make some time this weekend to look over it.

**Comment by kephale** [comment]
Sure, no rush. It is just like 3 lines, but I'm pip installing the branch now anyway, so this doesn't block me anymore.

**Comment by hanslovsky** [comment]
Can you share an example path in the `~/.jgo` cache? I would expect something like
```bash
~/.jgo/${groupId}/${artifactId}/${version}/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```
Is that correct?

As a user, can I see what the coordinate is for a workspace/hash? I think it would make sense to add a file to the workspace that shows `coordinate` or `coordinate[1:]`?
This file may also be helpful in the (extremely unlikely) case of a hash collision - jgo could throw an error instead of executing the wrong Java application.

**Comment by kephale** [comment]
`.jgo/sc.fiji/bigdataviewer-vistools/1.0.0-beta-29-SNAPSHOT+eba447da3454eafae1d5fd4a362d3457b84d0c5a20db7e40767c390d1dab6cba`

This solved my use case, and I was able to move on to the work it blocked. Saving the coordinate to file makes sense, will put it on the TODO.

**Comment by kephale** [comment]
@hanslovsky okey doke. I adjusted the path and added the coordinates file as well:

```
$ cat ~/.jgo/net.imagej/imagej/2.1.0/ad412f409ae00c86c7c3f165d0d787ed4dd7a42191903e4f0256bebee4b4fa45/coordinates.txt 
net.imagej:imagej:2.1.0
graphics.scenery:scenery:937ba10
org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.20
org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9
sc.fiji:bigdataviewer-core:10.1.1-SNAPSHOT
sc.iview:sciview:f4dd286
```

**Review by hanslovsky — APPROVED** [review]
Looks good to me, will leave it to @ctrueden to merge it.

**Comment by kephale** [comment]
bump

**Comment by kephale** [comment]
bump

**Comment by cthoyt** [comment]
I would suggest using [`black`](https://github.com/psf/black) to deterministically reformat the whole package. I could send a PR for that

**Comment by cthoyt** [comment]
@ctrueden now that this is merged, do you think you can mint a new release to PyPI?

**Comment by ctrueden** [comment]
> do you think you can mint a new release to PyPI?

@cthoyt I pushed jgo 1.0.2 to PyPI. Please let me know how it works for you!

**Pull request merged**
