### PR TITLE
Log first-time start up and warn about potentially slow start-up time

### LINKED ISSUE #40: Log to command line when a main class is run for the first time and might take a while to start
Unsuspecting users could get confused or frustrated, logging should help!

https://github.com/saalfeldlab/paintera/issues/233

### PR DESCRIPTION
**Pull request by hanslovsky**
Things to consider:
 1. The actual message
 2. currently, this message only shows with the `-v` flag in `jgo.sh`. Should we add another log level `warn` that does not check for `verbose`?

cc @ctrueden 

fixes #40

### CODE REVIEW

**Comment by ctrueden** [comment]
I agree that another log level would be good. The name "warn" is a bit weird, because the message here is more of an "FYI" than a "warning: something might be wrong" style message.

We will also need to add a quiet flag (`-q`?) to suppress even this level of output, in case it interferes with scripts etc.

Maybe something like:
```shell
notice() { test ! $quiet && echo "$@"; }
```
?

**Comment by hanslovsky** [comment]
I updated with a `notice` function:
```sh
$ ./jgo.sh org.scijava:parsington 1+3
4
$ rm -rf ~/.jgo/org.scijava
$ ./jgo.sh org.scijava:parsington 1+3
First time start-up may be slow. Downloaded dependencies will be cached for shorter start-up times in subsequent executions.
$ rm -rf ~/.jgo/org.scijava
$ ./jgo.sh -q org.scijava:parsington 1+3
4
$ ./jgo.sh org.scijava:parsington 1+3
4
```

Let me know if that satisfies your requirements @ctrueden

**Comment by hanslovsky** [comment]
Also added the `-q/--quiet` flag to Python jgo in 24c6def. Note that there is only one call to `print` in the entire Python package that also prints an empty string. I did not deem it necessary to add a check for that in the Python version. The Python log level can be fine-tuned with the `--log-level` flag now.

**Comment by hanslovsky** [comment]
Thanks for reviewing this @ctrueden

**Pull request merged**
